name: Upload-Artifacts

on:
  workflow_run:
    workflows: [Blockifier-CI-Test]
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Commit hash - 1
        # if: ${{ github.event_name == 'pull_request' }}
        env:
          COMMIT_SHA: ${{ github.event.workflow_run.head_commit.id }}
        run: |
          echo "SHORT_HASH=${COMMIT_SHA:0:7}" >> $GITHUB_ENV
          echo "COMMIT_SHA=${COMMIT_SHA}" >> $GITHUB_ENV
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.COMMIT_SHA }}

      - name: Verify current branch
        run: git branch --show-current

      - name: the workflow run URL
        run: |
          echo "The workflow run URL is: ${{ env.GITHUB_RUN_URL }}"
          echo "The workflow run GITHUB_API_URL is: ${{ env.GITHUB_API_URL}}"
          echo "*******"
          echo "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
          echo "*******"
          echo "The workflow run number is: ${{ github.run_number }}"
          echo "The workflow run name is: ${{ github.run_id }}"


      - name: Get PR Number 1
          # if: github.event.workflow_run.pull_requests != ''
        run: |
          pr_number=$(gh pr list --head "${{ github.event.workflow_run.head_branch }}" --json number --jq '.[0].number')
          echo "PR_NUMBER=$pr_number" >> $GITHUB_ENV
          echo "The workflow run URL is: $GITHUB_RUN_URL"

      - name: Checkout repository
        uses: actions/checkout@v3

      # - name: Get Pull Request Number - 2
      #   id: get_pr
      #   run: |
      #     pr=39
      #     echo "PR_NUMBER=$pr" >> $GITHUB_ENV
      #     echo "pr num is: $pr"

      - name: Add a comment to the PR
        if: env.PR_NUMBER != ''
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              issue_number: process.env.PR_NUMBER,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "This is a comment added by the workflow."
            })

      - name: Authenticate with GCS
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: ${{ secrets.NADIN_TEST_FORK_BUCKET_ACCESS_KEY }}


      - name: ls
        run: ls

      - name: Upload binary to GCP
        id: upload_file
        uses: "google-github-actions/upload-cloud-storage@v2"
        with:
          path: "upload_to_gcp.txt"
          destination: "nadin-test-fork/${{ env.SHORT_HASH }}/"



  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'
